In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [2]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [4]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [5]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [6]:
np.random.randint(50,101,size=(50, 5))

array([[ 74,  68,  65,  98,  67],
       [ 99,  75,  59,  58,  91],
       [ 66,  65,  88,  77,  82],
       [ 85,  89,  86,  66,  90],
       [ 69,  91,  74,  96,  95],
       [ 63,  60,  92,  82,  66],
       [ 56,  87,  50,  96,  97],
       [ 74,  87,  59,  77,  89],
       [ 97,  82,  66,  68,  81],
       [ 66,  94,  80, 100,  85],
       [ 88,  53,  70,  96,  55],
       [ 90,  59,  82,  69,  75],
       [ 72,  84,  78,  87,  63],
       [ 94,  82,  51,  95,  81],
       [ 92,  74,  84,  68,  53],
       [ 61,  89,  84,  80,  82],
       [100,  78,  72,  89,  63],
       [ 73,  84,  64,  76,  75],
       [ 77,  53,  81,  84,  93],
       [ 89,  76,  50,  99,  80],
       [ 60,  73,  61,  82,  63],
       [ 61,  66,  69,  52,  81],
       [ 90,  51, 100,  65,  50],
       [ 93,  57,  58,  96,  85],
       [ 92,  61,  94,  59,  93],
       [ 56,  70,  77,  53,  70],
       [ 63,  51,  98,  68,  52],
       [ 98,  81,  54,  80,  76],
       [ 72, 100,  73,  74,  51],
       [ 92,  